version: 2
jobs:
  build:

    docker:
      - image: circleci/node:10.15

    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo

    steps:
      - checkout

      - run:
          name: install gitbook
          command: yarn install

      - run:
          name: build docs
          command: |
            npm run gitbook install
            npm run gitbook init
            npm run gitbook build

      - run:
          name: push to gh-pages branch
          command: npm run gh-pages -d _book
