version: 2
jobs:

  build:

    docker:
      - image: circleci/node:10.15

    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo

    steps:
      - checkout

      - run:
          name: configure git
          command: |
            git config --global user.email "takahiro0914@live.jp"
            git config --global user.name "OriishiTakahiro"

      - run:
          name: install gitbook
          command: yarn install

      - run:
          name: build docs
          command: |
            yarn run gitbook install
            yarn run gitbook init
            yarn run gitbook build

      - run:
          name: push to gh-pages branch
          command: yarn run gh-pages -d _book
